---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod
  name: testpod
  namespace: default
spec:
  containers:
  - args:
    - "sleep"
    - "3600"
    image: bitnami/kubectl
    name: testpod
  restartPolicy: Never
  serviceAccountName: pod-viewer
